# Generated by Django 2.2.19 on 2022-01-15 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220114_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredient',
            options={'ordering': ['ingredient', 'amount'], 'verbose_name': 'Количество ингридента', 'verbose_name_plural': 'Список ингридентов и их количество'},
        ),
    ]
